// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC73yH176_UGNTzXgJKRiVHDTvE_GEWAtM',
    appId: '1:757222958410:web:62390eae4de62a28744db3',
    messagingSenderId: '757222958410',
    projectId: 'saloonprojet-4b216',
    authDomain: 'saloonprojet-4b216.firebaseapp.com',
    storageBucket: 'saloonprojet-4b216.appspot.com',
    measurementId: 'G-RZ5JKRM2HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCONl2Fr2Dq6EUZpcUFzB5nQKNo_2bxayE',
    appId: '1:757222958410:android:a78ac4879e289b38744db3',
    messagingSenderId: '757222958410',
    projectId: 'saloonprojet-4b216',
    storageBucket: 'saloonprojet-4b216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pYuiPT9LjVL55Noe0MuAPikIcQEvU_s',
    appId: '1:757222958410:ios:f0ef85bd968c0941744db3',
    messagingSenderId: '757222958410',
    projectId: 'saloonprojet-4b216',
    storageBucket: 'saloonprojet-4b216.appspot.com',
    iosBundleId: 'com.example.scissorsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9pYuiPT9LjVL55Noe0MuAPikIcQEvU_s',
    appId: '1:757222958410:ios:bf73a4bb6d6c0956744db3',
    messagingSenderId: '757222958410',
    projectId: 'saloonprojet-4b216',
    storageBucket: 'saloonprojet-4b216.appspot.com',
    iosBundleId: 'com.example.scissorsProject.RunnerTests',
  );
}
