// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWHjGGbm_e2-5LoDW-mYydiK7v9TA92YE',
    appId: '1:607405541160:web:b7a6c718c724d6d5da321d',
    messagingSenderId: '607405541160',
    projectId: 'scissorproject-f043c',
    authDomain: 'scissorproject-f043c.firebaseapp.com',
    storageBucket: 'scissorproject-f043c.appspot.com',
    measurementId: 'G-K5F8GNEDS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH2_wMUIXwpIXtDv_BXcUwWgFmZSIyiaE',
    appId: '1:607405541160:android:86e10cdcd22d5ad8da321d',
    messagingSenderId: '607405541160',
    projectId: 'scissorproject-f043c',
    storageBucket: 'scissorproject-f043c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8uw8rdCnJN_ox46NX-dDEfypf3WKy9g',
    appId: '1:607405541160:ios:beb14bcd7c61f3fdda321d',
    messagingSenderId: '607405541160',
    projectId: 'scissorproject-f043c',
    storageBucket: 'scissorproject-f043c.appspot.com',
    iosBundleId: 'com.example.scissorsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs8uw8rdCnJN_ox46NX-dDEfypf3WKy9g',
    appId: '1:607405541160:ios:368168432d6eece5da321d',
    messagingSenderId: '607405541160',
    projectId: 'scissorproject-f043c',
    storageBucket: 'scissorproject-f043c.appspot.com',
    iosBundleId: 'com.example.scissorsProject.RunnerTests',
  );
}
